import type { CSSProperties } from "react";

export const s = {
  pageHeader: {
    padding: "24px 32px 10px",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
  } satisfies CSSProperties,
  pageTitle: { fontSize: 20, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  repoName: { fontFamily: "var(--font-mono)" } satisfies CSSProperties,
  pageSubtitle: { fontSize: 13.5, color: "var(--text-secondary)", margin: "4px 0 0" } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  feedback: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  shareField: {
    fontSize: 12.5,
    padding: "6px 8px",
    minWidth: 280,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  content: { padding: "14px 32px 44px" } satisfies CSSProperties,
  banner: {
    fontSize: 13,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--text-primary)",
    marginBottom: 14,
  } satisfies CSSProperties,
  layout: { display: "flex", gap: 28, alignItems: "flex-start" } satisfies CSSProperties,
  nav: {
    position: "sticky",
    top: 16,
    width: 190,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  navTitle: {
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "var(--text-muted)",
    margin: "0 0 6px",
  } satisfies CSSProperties,
  navLink: {
    fontSize: 13.5,
    padding: "5px 8px",
    borderRadius: 6,
    color: "var(--text-secondary)",
    textDecoration: "none",
  } satisfies CSSProperties,
  sections: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "12px 14px",
    background: "transparent",
    border: "none",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  cardBody: { padding: "0 14px 14px" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  prose: { fontSize: 13.5, lineHeight: 1.6, color: "var(--text-primary)" } satisfies CSSProperties,
  chip: {
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    padding: "1px 6px",
    borderRadius: 4,
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  graphWrap: { overflowX: "auto", margin: "12px 0" } satisfies CSSProperties,
  legend: { display: "flex", flexWrap: "wrap", gap: 12, fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  legendItem: { display: "inline-flex", alignItems: "center", gap: 5 } satisfies CSSProperties,
  edgeList: { fontSize: 12.5, color: "var(--text-secondary)", margin: "8px 0 0", paddingLeft: 20 } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 8,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  path: { fontFamily: "var(--font-mono)", fontSize: 13, wordBreak: "break-all" } satisfies CSSProperties,
  meta: { fontSize: 12.5, color: "var(--text-secondary)", margin: "2px 0 0" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  list: { margin: 0, paddingLeft: 22, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  command: {
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  } satisfies CSSProperties,
  comment: { color: "var(--text-muted)" } satisfies CSSProperties,
  taskCard: {
    padding: 12,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 10,
  } satisfies CSSProperties,
  taskTitle: { fontSize: 14, fontWeight: 600, margin: 0 } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 8 } satisfies CSSProperties,
  chipLink: {
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    color: "var(--accent)",
    textDecoration: "none",
  } satisfies CSSProperties,
};
