import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8, flexWrap: "wrap" } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 14, lineHeight: 1.5 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    marginBottom: 8,
  } satisfies CSSProperties,
  rowDrop: { borderColor: "var(--accent)" } satisfies CSSProperties,
  grip: { color: "var(--text-muted)", cursor: "grab", display: "grid", placeItems: "center" } satisfies CSSProperties,
  path: {
    fontSize: 13,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  meta: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  warn: { fontSize: 12, color: "var(--warn, #f59e0b)", whiteSpace: "nowrap" } satisfies CSSProperties,
  moveBtns: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  actions: { display: "flex", gap: 10, marginTop: 14, alignItems: "center" } satisfies CSSProperties,
  savedNote: { fontSize: 13, color: "var(--ok)" } satisfies CSSProperties,
  previewMeta: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 14 } satisfies CSSProperties,
  previewBody: { fontSize: 14, color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
