import type { CSSProperties } from "react";
import { CARD_WIDTH, LOGO_SIZE, PAGE_PADDING } from "./constants";

/** Co-located styles for AddRepoView (extracted from inline styles). */
export const s = {
  page: {
    width: "100%",
    minHeight: "100vh",
    background: "var(--bg-primary)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: PAGE_PADDING,
  } satisfies CSSProperties,
  logoRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 32 } satisfies CSSProperties,
  logoBox: {
    width: LOGO_SIZE,
    height: LOGO_SIZE,
    borderRadius: 8,
    background: "var(--text-primary)",
    display: "grid",
    placeItems: "center",
  } satisfies CSSProperties,
  logoIcon: { color: "var(--bg-primary)" } satisfies CSSProperties,
  logoText: { fontSize: 20, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  card: {
    position: "relative",
    width: CARD_WIDTH,
    maxWidth: "100%",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 14,
    padding: 36,
    boxShadow: "var(--shadow-modal)",
  } satisfies CSSProperties,
  closeBtn: { position: "absolute", top: 16, right: 16 } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  body: {
    fontSize: 14,
    color: "var(--text-secondary)",
    marginTop: 8,
    marginBottom: 28,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  settingsLink: { color: "var(--accent-text)" } satisfies CSSProperties,
  errorRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 8,
    background: "var(--crit-bg)",
    border: "1px solid rgba(239,68,68,0.25)",
    marginTop: 16,
  } satisfies CSSProperties,
  errorIcon: { color: "var(--crit)" } satisfies CSSProperties,
  errorText: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  actionsRow: { display: "flex", gap: 12, alignItems: "center", marginTop: 24 } satisfies CSSProperties,
  actionsSpacer: { flex: 1 } satisfies CSSProperties,
  footer: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginTop: 24,
    display: "inline-flex",
    gap: 8,
    alignItems: "center",
  } satisfies CSSProperties,
} as const;
