import type { CSSProperties } from "react";

export const s = {
  overviewGrid: {
    display: "grid",
    // Two columns when there is room, stacked on narrow widths.
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: 20,
    alignItems: "start",
  } satisfies CSSProperties,
  descriptionBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    fontSize: 14,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  intentHeaderRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  intentSummary: {
    margin: 0,
    color: "var(--text-primary)",
    fontWeight: 500,
  } satisfies CSSProperties,
  intentBadges: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  intentScopeGroup: {
    marginTop: 12,
  } satisfies CSSProperties,
  intentScopeLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  intentScopeList: {
    margin: 0,
    paddingLeft: 18,
  } satisfies CSSProperties,
  intentEmpty: {
    margin: 0,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  intentFooter: {
    marginTop: 14,
  } satisfies CSSProperties,
  blastDegradedRow: {
    marginBottom: 12,
  } satisfies CSSProperties,
  blastStatsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 12,
  } satisfies CSSProperties,
  blastStatsGroup: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  blastStat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  viewToggle: {
    display: "inline-flex",
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
  } satisfies CSSProperties,
  viewToggleButton: {
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    padding: "5px 12px",
    cursor: "pointer",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  viewToggleButtonActive: {
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  blastEmpty: {
    margin: 0,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  blastGroups: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  blastGroup: {
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  blastGroupHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    cursor: "pointer",
  } satisfies CSSProperties,
  blastGroupSymbol: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "var(--font-mono, monospace)",
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  blastGroupCount: {
    color: "var(--text-muted)",
    fontSize: 12,
    marginLeft: "auto",
  } satisfies CSSProperties,
  blastGroupBody: {
    minWidth: 0,
    borderTop: "1px solid var(--border)",
    padding: "8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  blastGroupEmpty: {
    color: "var(--text-muted)",
    fontSize: 13,
  } satisfies CSSProperties,
  blastCallerRow: {
    fontSize: 13,
    display: "flex",
    alignItems: "flex-start",
    gap: 4,
    minWidth: 0,
  } satisfies CSSProperties,
  blastCallerPrefix: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  /** Lets a long unbroken file path wrap instead of overflowing the card. */
  blastCallerPath: {
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  blastImpactRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginTop: 6,
  } satisfies CSSProperties,
  priorPrsSection: {
    marginTop: 16,
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  priorPrsHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    cursor: "pointer",
  } satisfies CSSProperties,
  priorPrsTitle: {
    color: "var(--text-primary)",
    fontWeight: 600,
    fontSize: 13,
  } satisfies CSSProperties,
  priorPrsCount: {
    color: "var(--text-muted)",
    fontSize: 12,
    marginLeft: "auto",
  } satisfies CSSProperties,
  priorPrsBody: {
    borderTop: "1px solid var(--border)",
    padding: "8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  priorPrRow: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  priorPrLink: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--accent-text)",
    textDecoration: "none",
  } satisfies CSSProperties,
  priorPrMeta: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  priorPrTakeaway: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  briefBody: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  briefSummary: {
    margin: 0,
    color: "var(--text-primary)",
    fontWeight: 500,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  briefMuted: {
    margin: 0,
    color: "var(--text-muted)",
    fontSize: 13,
  } satisfies CSSProperties,
  briefNotice: {
    margin: 0,
    padding: "8px 12px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
  briefError: {
    margin: 0,
    padding: "8px 12px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  briefSectionLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  briefList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  briefOrderedList: {
    margin: 0,
    paddingLeft: 20,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  riskItem: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  riskTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  riskTitle: {
    fontWeight: 600,
    color: "var(--text-primary)",
    fontSize: 13.5,
  } satisfies CSSProperties,
  riskExplanation: {
    margin: 0,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  riskRefs: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
    marginTop: 2,
  } satisfies CSSProperties,
  fileLink: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    color: "var(--accent-text)",
    textDecoration: "underline",
    textAlign: "left",
    wordBreak: "break-all",
  } satisfies CSSProperties,
} as const;

export function severityStyle(color: string, bg: string): CSSProperties {
  return {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "1px 7px",
    borderRadius: 999,
    fontSize: 11.5,
    fontWeight: 600,
    color,
    background: bg,
  };
}
